package frc.robot.subsystems.Elevator;

public enum ElevatorState {
    BASE, INTAKE_CORAL, LEVEL0, LEVEL1 , LEVEL2, LEVEL3, ALGAE_LOW_PROCESSOR, ALGAE_HIGH_PROCESSOR, ALGAE_LOW_IN, ALGAE_HIGH_IN
    , ALGAE_LOW_NET, ALGAE_HIGH_NET, ALGAE_HOLD_NET, ALGAE_THROW_NET
}
